#+BEGIN_COMMENT
.. title: Data Leakages
.. slug: data-leakages
.. date: 2018-09-08 18:31:29 UTC-07:00
.. tags: assignment dataleaks
.. category: assignment
.. link: 
.. description: Data Leakage example.
.. type: text
#+END_COMMENT
#+OPTIONS: ^:{}
#+TOC: headlines 1

* Introduction

In this programming assignment we will illustrate a very severe data leakage, that can often be found in competitions, where the pairs of object should be scored, e.g. predict /1/ if two objects belong to the same class and /0/ otherwise. 

The data in this assignment is taken from a real competition, and the funny thing is that *we will not use the training set at all* and still achieve an accuracy score of almost 100% - we will just exploit the leakage.

* Imports

#+BEGIN_SRC ipython :session leakage :results none
import warnings
warnings.filterwarnings("ignore", message="numpy.dtype size changed")
warnings.filterwarnings("ignore", message="numpy.ufunc size changed")
#+END_SRC

#+BEGIN_SRC ipython :session leakage :results none
# from pypi
import numpy
import pandas
import scipy.sparse
#+END_SRC

* Load the data

Let's load the test data. Note, that we don't have any training data here, just test data. Moreover, *we will not even use any features* of test objects. All we need to solve this task is the file with the indices for the pairs, that we need to compare.

Let's load the data with test indices.

#+BEGIN_SRC ipython :session leakage :results output
test = pandas.read_csv('../data/test_pairs.csv')
print(test.head(10))
#+END_SRC

#+RESULTS:
#+begin_example
   pairId  FirstId  SecondId
0       0     1427      8053
1       1    17044      7681
2       2    19237     20966
3       3     8005     20765
4       4    16837       599
5       5     3657     12504
6       6     2836      7582
7       7     6136      6111
8       8    23295      9817
9       9     6621      7672
#+end_example


We don't know what the data represents in this case, but you can give them an arbitrary meaning. You could, for example, can think that there is a test dataset of images, and each image is assigned a unique `Id` from $0$ to $N-1$ (N -- is the number of images). In the dataframe from above `FirstId` and `SecondId` point to these `Id`'s and define pairs, that we should compare: e.g. do both images in the pair belong to the same class or not. So, for example for the first row: if images with `Id=1427` and `Id=8053` belong to the same class, we should predict $1$, and $0$ otherwise. 

But in our case we don't really care about the images, and how exactly we compare the images (as long as the output is binary).  

**We suggest you to try to solve the puzzle yourself first.** You need to submit a `.csv` file with columns `pairId` and `Prediction` to the grader. The number of submissions allowed is made pretty huge to let you explore the data without worries. The returned score should be very close to $1$.

**If you do not want to think much** -- scroll down and follow the instructions below.

* EDA and leakage intuition

As we already know, the key to discover data leakages is careful EDA. So let's start our work with some basic data exploration and build an intuition about the leakage.

First, check, how many different `id`s are there: concatenate `FirstId` and `SecondId` and print the number of unique elements. Also print minimum and maximum value for that vector.

#+BEGIN_SRC ipython :session leakage :results output :exports both
smashed = test.FirstId.apply(lambda row: str(row)) + ',' + test.SecondId.apply(lambda row: str(row))
print(smashed.head())
#+END_SRC

#+RESULTS:
: 0      1427,8053
: 1     17044,7681
: 2    19237,20966
: 3     8005,20765
: 4      16837,599
: dtype: object

#+BEGIN_SRC ipython :session leakage :results output :exports both
print("Unique Pairs: {}".format(len(smashed.unique())))
print("Total Pairs: {}".format(len(test)))
print(smashed.min())
print(smashed.max())
#+END_SRC

#+RESULTS:
: Unique Pairs: 368538
: Total Pairs: 368550
: 0,10552
: 9999,8996


and then print how many pairs we need to classify (it is basically the number of rows in the test set)

#+BEGIN_SRC ipython :session leakage :results output :exports both
print(len(test))
print(len(test) - len(smashed.unique()))
#+END_SRC

#+RESULTS:
: 368550
: 41


Now print, how many distinct pairs it would be possible to create out of all "images" in the dataset?   

#+BEGIN_SRC ipython :session leakage :results output :exports both
catted = pandas.concat([test.FirstId, test.SecondId])
image_count = len(catted.unique())
print("Unique image IDs: {:,}".format(image_count))
print("Handshakes: {:,}".format(int((image_count * (image_count - 1))/2)))
#+END_SRC

#+RESULTS:
: Unique image IDs: 26,325
: Handshakes: 346,489,650

So the number of pairs we are given to classify is very very small compared to the total number of pairs. 

To exploit the leak we need to **assume (or prove)**, that the total number of positive pairs is small, compared to the total number of pairs. For example: think about an image dataset with $1000$ classes, $N$ images per class. Then if the task was to tell whether a pair of images belongs to the same class or not, we would have $1000\frac{N(N-1)}{2}$ positive pairs, while total number of pairs was $\frac{1000N(1000N - 1)}{2}$.

Another example: in [[https://www.kaggle.com/c/quora-question-pairs][Quora competitition]] the task was to classify whether a pair of questions are duplicates of each other or not. Of course, total number of question pairs is very huge, while number of duplicates (positive pairs) is much much smaller.

Finally, let's get a fraction of pairs of class `1`. We just need to submit a constant prediction "all ones" and check the returned accuracy. Create a dataframe with columns `pairId` and `Prediction`, fill it and export it to `.csv` file. Then submit to grader and examine grader's output. 

#+BEGIN_SRC ipython :session leakage :results output :exports both
all_ones = test[["pairId"]].copy()
all_ones["Prediction"] = [1] * len(all_ones)
print(all_ones.head())
all_ones.to_csv("../data/leakages/submission.csv", index=False)
#+END_SRC

#+RESULTS:
:    pairId  Prediction
: 0       0           1
: 1       1           1
: 2       2           1
: 3       3           1
: 4       4           1

The submission output was:

#+BEGIN_EXAMPLE
Your accuracy score is 0.500000. It seems too low, try one more time.
#+END_EXAMPLE

So, we assumed the total number of pairs is much higher than the number of positive pairs, but it is not the case for the test set. It means that the test set is constructed not by sampling random pairs, but with a specific sampling algorithm. Pairs of class `1` are oversampled.

Now think, how we can exploit this fact? What is the leak here? If you get it now, you may try to get to the final answer yourself, othewise you can follow the instructions below.   

* Building a magic feature

In this section we will build a magic feature, that will solve the problem almost perfectly. The instructions will lead you to the correct solution, but please, try to explain the purpose of the steps we do to yourself -- it is very important.

** Incidence matrix

First, we need to build an [[https://en.wikipedia.org/wiki/Incidence_matrix][incidence matrix]]. You can think of pairs `(FirstId, SecondId)` as of edges in an undirected graph. 

The incidence matrix is a matrix of size `(maxId + 1, maxId + 1)`, where each row (column) `i` corresponds `i-th` `Id`. In this matrix we put the value `1` to the position `[i, j]`, if and only if a pair `(i, j)` or `(j, i)` is present in  a given set of pairs `(FirstId, SecondId)`. All the other elements in the incidence matrix are zeros.   
 
**Important!** The incidence matrices are typically very very sparse (small number of non-zero values). At the same time incidence matrices are usually huge in terms of total number of elements, and it is **impossible to store them in memory in dense format**. But due to their sparsity incidence matrices **can be easily represented as sparse matrices**. If you are not familiar with sparse matrices, please see [[https://en.wikipedia.org/wiki/Sparse_matrix][wikipedia]] and [[https://docs.scipy.org/doc/scipy/reference/sparse.html][scipy.sparse reference]]. Please, use any of `scipy.sparse` constructors to build incidence matrix. 

For example, you can use this constructor: `scipy.sparse.coo_matrix((data, (i, j)))`. We highly recommend to learn to use different `scipy.sparse` constuctors, and matrices types, but if you feel you don't want to use them, you can always build this matrix with a simple `for` loop. You will need first to create a matrix using `scipy.sparse.coo_matrix((M, N), [dtype])` with an appropriate shape `(M, N)` and then iterate through `(FirstId, SecondId)` pairs and fill corresponding elements in matrix with ones. 

**Note**, that the matrix should be symmetric and consist only of zeros and ones. It is a way to check yourself.

#+BEGIN_SRC ipython :session leakage :results none
data = numpy.ones(len(test))
inc_mat = scipy.sparse.coo_matrix((data, (test.FirstId, test.SecondId)))

# Sanity checks
assert inc_mat.max() == 1
assert inc_mat.sum() == 736872
#+END_SRC

# It is convenient to have matrix in `csr` format eventually.

# In[ ]:


inc_mat = inc_mat.tocsr()


# ## Now build the magic feature

# Why did we build the incidence matrix? We can think of the rows in this matix as of representations for the objects. `i-th` row is a representation for an object with `Id = i`. Then, to measure similarity between two objects we can measure similarity between their representations. And we will see, that such representations are very good.

# Now select the rows from the incidence matrix, that correspond to `test.FirstId`'s, and `test.SecondId`'s.

# In[ ]:


# Note, scipy goes crazy if a matrix is indexed with pandas' series. 
# So do not forget to convert `pd.series` to `np.array`
# These lines should normally run very quickly 

rows_FirstId   = # YOUR CODE GOES HERE
rows_SecondId  = # YOUR CODE GOES HERE


# Our magic feature will be the *dot product* between representations of a pair of objects. Dot product can be regarded as similarity measure -- for our non-negative representations the dot product is close to 0 when the representations are different, and is huge, when representations are similar. 
# 
# Now compute dot product between corresponding rows in `rows_FirstId` and `rows_SecondId` matrices.

# In[ ]:


# Note, that in order to do pointwise multiplication in scipy.sparse you need to use function `multiply`
# regular `*` corresponds to matrix-matrix multiplication

f = # YOUR CODE GOES HERE

# Sanity check
assert f.shape == (368550, )


# That is it! **We've built our magic feature.** 

# # From magic feature to binary predictions

# But how do we convert this feature into binary predictions? We do not have a train set to learn a model, but we have a piece of information about test set: the baseline accuracy score that you got, when submitting constant. And we also have a very strong considerations about the data generative process, so probably we will be fine even without a training set. 

# We may try to choose a thresold, and set the predictions to 1, if the feature value `f` is higer than the threshold, and 0 otherwise. What threshold would you choose? 

# How do we find a right threshold? Let's first examine this feature: print frequencies (or counts) of each value in the feature `f`.

# In[ ]:


# For example use `np.unique` function, check for flags

print # YOUR CODE GOES HERE


# Do you see how this feature clusters the pairs? Maybe you can guess a good threshold by looking at the values? 
# 
# In fact, in other situations it can be not that obvious, but in general to pick a threshold you only need to remember the score of your baseline submission and use this information. Do you understand why and how?  

# Choose a threshold below: 

# In[ ]:


pred = f > # SET THRESHOLD HERE


# # Finally, let's create a submission

# In[ ]:


submission = test.loc[:,['pairId']]
submission['Prediction'] = pred.astype(int)

submission.to_csv('submission.csv', index=False)


# Now submit it to the grader! It is not possible to submit directly from this notebook, as we need to submit a `csv` file, not a single number (limitation of Coursera platform). 
# 
# To download `submission.csv` file that you've just produced <a href='./submission.csv'>click here</a> (if the link opens in browser, right-click on it and shoose "Save link as"). Then go to [assignment page](https://www.coursera.org/learn/competitive-data-science/programming/KsASv/data-leakages/submission) and submit your `.csv` file in 'My submission' tab.
# 
# 
# If you did everything right, the score should be very high.

# **Finally:** try to explain to yourself, why the whole thing worked out. In fact, there is no magic in this feature, and the idea to use rows in the incidence matrix can be intuitively justified.

# # Bonus

# Interestingly, it is not the only leak in this dataset. There is another totally different way to get almost 100% accuracy. Try to find it!
