#+BEGIN_COMMENT
.. title: Exploratory Data Analysis
.. slug: exploratory-data-analysis
.. date: 2018-09-03 21:24:53 UTC-07:00
.. tags: notes data
.. category: notes
.. link: 
.. description: Notes on exploratorry data analysis.
.. type: text
#+END_COMMENT

* Building Your Intuition About the Data
  The first thing to do is to see if you can build up a mental model of what the data is about.
** Get Domain Knowledge
   Find out something about the topic that the data describes.
** Check if the Data is intuitive
   See if there are any strange values and see if it makes sense given the data description.
** Understand how the data was generated
   Is any of it synthetic? Was the training data generated the same way as the testing data?
* Exploring Anonymized Data
  Organizers sometimes encode data so you can't tell what it is.
** Try To Decode the Data
   You generally won't be able to figure out what the data is if it's encoded, but sometimes they were created using simple shifting schemes that will let you figure out their original values.
** Explore Individual Features
   Even if you don't know what the data is, it's important to know what type of data it is so that you can use the right data preprocessing for your model.
   - =df.dtypes=
   - =df.info()=
   - =x.value_counts()=
   - =x.isnull()=
* Visualizations
** Features
*** Histograms
    This is useful for seeing the shape of the data.
    - =pyplot.hist(x)=
*** Index vs Value
    This will show you how well distributed the data is within the data frame. Horizontal lines indicate repeated values and empty bands show areas where none of the data had this value. If you don't have vertical lines then the data was probably shuffled.
    - =pyplot.plot(x, '.')=
*** Index vs Valuue Colorede By Class Label
    If you plot the classes with different colors you can see if there are clusters and clear separations between them. (=y= in the function call has the target values).
    - =pyplot.scatter(range(len(x)), x, c=y)=
*** Plot Other Things
    - Row vs Feature
    - Nan-values
    - Value Counts
** Relationships
*** Scatter Plots
**** Pairwise Relationships
    To make it eaiser to see relationships, you can plot them in pairs.
    - =pyplot.scatter(x1, x2)=
**** Compare the Test Set
     Plot the features and the test-set (using different colors) to see how well your training data matches your test data.
**** Scatter Matrix
     Pandas has a convenience function that will plot all the pairwise scatter-plots for you.
     - =pandas.scatter_matrix(X)=
*** Corellation
    Plot the corellation matrix to see if there are feature-pairs that are related so you can make a new feature out of them and see if they help.
    - =X.corr(), pyplot.matshow()=

 A straight correllation matrix might give you a sense of how correllated the features are, but it's more useful to use a clustering algorithm to see if there are groups within the correlation matrix.
*** Plot Statistics
    Try plotting mean, differences, combination counts, etc. and see if you can create groups out of them.
* Data Set Cleaning
** Duplicated and Constant Features
   Sometimes a feature will have the same value in all the rows. If it's this way in both the training and test sets you can just remove it, but if there are different values in the test set you have to figure out how to handle them.
   - =x_train.nunique(axis="columns") == 1=

Sometimes columns will get duplicated in which case you should drop one of them.

 - =x_train.T.drop_duplicates()=

This can happen with rows as well, but it can be harder to decide whether this is a mistake or not.
** Non-shuffled Data
   If you plot the mean as a horizontal line the data should be evenly distributed around it, if not it might not have been shuffled and there could be an inadvertent pattern in the data. You might not be able to use it, but you should understand all the things about the data that you can find out.
* Quiz
** One
   Suppose we are given a data set with features /X/, /Y/, and /Z/. Can you recover /z/ as a function of /x/ and /y/?
   - [X] Z = X/Y
   - [ ] Z = X - Y
   - [ ] Z = X + Y
   - [ ] Z = XY
** Two
   What value do the red dots have?
   0.5 (wrong)
   2 (next try)
** Three
   What hypothesis about X can we not reject based on the plots?
   - [X] X is a counter or label encoded categorical feature
   - [ ] X can be the temperature (in Celsius) in different cities at different times. (the values are probably out of range)
   - [ ] X can take a value of zero (The log plot would have values at 0 but it doesn't)
   - [X] X takes only discrete values (the horizontal lines indicate that there are repeated values with discrete values)
   - [X] 2 <= X < 3 happens more frequently than 3 <= X < 4
** Four
   - [ ] Target is completely determined by coordinates (x,y)(x,y)(x,y), i.e. the label of the point is completely determined by point's position (x,y)(x,y)(x,y). Saying the same in other words: if we only had two features (x,y)(x,y)(x,y), we could build a classifier, that is accurate 100% of time.
   - [X] The top right plot is better than the top left in that everything you get from the top left can also be gotten from the top right, but not the other way around.
   - [X] standard deviation for jittering is the largest on the bottom right.
* Links
  - [[http://scikit-learn.org/stable/auto_examples/bicluster/plot_spectral_biclustering.html][Sorting Correlation Plots]]
